services:
  - type: web
    name: foodmatch-ai-api
    env: python
    envVars:
      PYTHON_VERSION: 3.10.14
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    autoDeploy: true
